from templates.template_manager import TemplateManager

_GENERATED_APP_VERSION = "0.1.0"


class CliFiles:
    """Build the minimal file mapping for a command-line application."""

    @staticmethod
    def build(
        project_name: str,
        package_name: str,
    ) -> dict[str, str]:
        template_manager = TemplateManager()

        return {
            "README.md": template_manager.get_readme(project_name),
            ".gitignore": template_manager.get_gitignore(),
            "requirements.txt": "",
            "pyproject.toml": template_manager.get_pyproject(project_name),
            f"{package_name}/__init__.py": "",
            f"{package_name}/__main__.py": CliFiles._build_main(),
            f"{package_name}/cli.py": CliFiles._build_cli(package_name),
            "tests/__init__.py": "",
        }

    @staticmethod
    def _build_main() -> str:
        return '''"""Run the generated command-line application as a module."""

from .cli import main


if __name__ == "__main__":
    raise SystemExit(main())
'''

    @staticmethod
    def _build_cli(package_name: str) -> str:
        return f'''"""Command-line interface for the generated application."""

import argparse
from collections.abc import Sequence


APP_VERSION = "{_GENERATED_APP_VERSION}"


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog={package_name!r},
        description="Minimal command-line application generated by ForgePy.",
    )
    parser.add_argument(
        "--version",
        action="version",
        version=f"%(prog)s {{APP_VERSION}}",
    )
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    build_parser().parse_args(argv)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
'''
